### ISSUE TITLE
'LottieAnimation' does not contain a definition for 'CreateCache' & 'LottieAnimation' does not contain a definition for 'ShouldCache'

### ISSUE THREAD

**Issue by babakmdi** [FrayxRulez/RLottie.UWP#1]
private LottieAnimation _animation;

   if (animation is LottieAnimation cached)
                    {
                        _cachingSemaphone.Wait();
                       
                        cached.CreateCache(256, 256);

                        _animationIsCaching = false;
                        _cachingSemaphone.Release();
                    }

        _animationShouldCache = animation.ShouldCache;

i Have this problem, the lottieanimation does not contain CreateCache and ShouldCache
what should i do ?

**Comment by FrayxRulez** [comment]
👋 it looks like you're using an outdated version of `LottieView`. 
`LottieAnimation` no longer supports `CreateCache`/`ShouldCache` as now frames get asynchronously cached as they get rendered.
This improves first time rendering and subsequent loadings (as after a full cache, json model won't be parsed at all)

**Comment by babakmdi** [comment]
its your code sir

https://github.com/FrayxRulez/Houseclub/tree/master/Clubhouse

in Voice Service
