### ISSUE TITLE
RLottie.pri not found

### ISSUE THREAD

**Issue by babakmdi** [FrayxRulez/RLottie.UWP#2]
i get this error ! :) 

![image](https://user-images.githubusercontent.com/65450661/122054149-aa724400-cdfc-11eb-8cb6-b2d1ff8d73a1.png)

**Comment by FrayxRulez** [comment]
The actual problem is that you miss `zlib`. The easiest way to get it is the following:
```powershell
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg.exe install zlib:arm64-uwp zlib:x64-uwp zlib:x86-uwp
./vcpkg.exe integrate install
```
